#!/usr/bin/env python
# -*- coding: utf8 -*

from iBrewConsole import *

#------------------------------------------------------
# iBrew
#
# Interface to Smarter Appliances
#
# https://github.com/Tristan79/iBrew
#
# Copyright © 2016 Tristan (@monkeycat.nl)
#
# The Dream Tea
#------------------------------------------------------

#------------------------------------------------------
# MAIN
#------------------------------------------------------

iBrewConsole().run(sys.argv[1:])

