#!/usr/bin/python
# -*- coding: utf8 -*

from iBrewConsole import *

#------------------------------------------------------
# iBrew
#
# Interface to iKettle 2.0 & SmarterCoffee Devices
#
# https://github.com/Tristan79/iBrew
#
# Copyright © 2016 Tristan (@monkeycat.nl)
#
# Intermezzo
#------------------------------------------------------

#------------------------------------------------------
# MAIN
#------------------------------------------------------

iBrewConsole().run(sys.argv[1:])

