all:
	@echo iBrew: Generating Smarter Protocol Description
	@echo "Smarter iKettle & Smarter Coffee protocol description\nGENERATED by iBrew (command: iBrew protocol)\nhttps://github.com/Tristan79/iBrew" > protocol.txt
	@date >> protocol.txt
	@python iBrew protocol >> protocol.txt
     
clean:
	@echo iBrew: Cleaning Up
	@rm -f *.pyc
	

